import type { Project, Member } from "./types"

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "AI 기반 학습 플랫폼",
    description:
      "인공지능을 활용한 맞춤형 학습 콘텐츠를 제공하는 웹 플랫폼입니다. 사용자의 학습 패턴을 분석하여 최적화된 학습 경로를 제안합니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["React", "Node.js", "TensorFlow", "MongoDB"],
    deadline: "2025-06-15",
    positions: ["백엔드 개발자", "AI 엔지니어", "UI/UX 디자이너"],
    owner: {
      name: "김철수",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "2",
    title: "블록체인 기반 중고거래 앱",
    description:
      "블록체인 기술을 활용한 안전한 중고거래 플랫폼입니다. 스마트 계약을 통해 거래의 투명성과 신뢰성을 보장합니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["React Native", "Solidity", "Ethereum", "Firebase"],
    deadline: "2025-07-01",
    positions: ["모바일 개발자", "블록체인 개발자", "백엔드 개발자"],
    owner: {
      name: "이영희",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "3",
    title: "실시간 협업 툴",
    description:
      "팀 프로젝트를 위한 실시간 협업 도구입니다. 문서 편집, 화상 회의, 일정 관리 등 다양한 기능을 제공합니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["Vue.js", "WebRTC", "Socket.io", "Express"],
    deadline: "2025-06-20",
    positions: ["프론트엔드 개발자", "백엔드 개발자"],
    owner: {
      name: "박민수",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "4",
    title: "건강 관리 모바일 앱",
    description: "사용자의 건강 데이터를 수집하고 분석하여 맞춤형 건강 관리 솔루션을 제공하는 모바일 앱입니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["Flutter", "Firebase", "Python", "TensorFlow"],
    deadline: "2025-07-10",
    positions: ["Flutter 개발자", "데이터 분석가", "UI/UX 디자이너"],
    owner: {
      name: "정지원",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "5",
    title: "AR 기반 인테리어 시뮬레이션",
    description: "증강현실 기술을 활용하여 실제 공간에 가구와 인테리어 요소를 배치해볼 수 있는 앱입니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["Unity", "ARKit", "ARCore", "C#"],
    deadline: "2025-08-01",
    positions: ["Unity 개발자", "3D 모델러", "AR 엔지니어"],
    owner: {
      name: "한지민",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "6",
    title: "음악 추천 알고리즘",
    description: "사용자의 음악 취향을 분석하여 개인화된 음악 추천 서비스를 제공하는 웹 애플리케이션입니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["Python", "Django", "React", "PostgreSQL"],
    deadline: "2025-07-15",
    positions: ["백엔드 개발자", "프론트엔드 개발자", "데이터 사이언티스트"],
    owner: {
      name: "최준호",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "7",
    title: "스마트 홈 IoT 시스템",
    description:
      "다양한 IoT 기기를 연동하여 스마트 홈 환경을 구축하는 프로젝트입니다. 음성 인식과 자동화 기능을 제공합니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["Raspberry Pi", "Python", "MQTT", "React"],
    deadline: "2025-08-10",
    positions: ["IoT 개발자", "백엔드 개발자", "프론트엔드 개발자"],
    owner: {
      name: "송미라",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "8",
    title: "지역 기반 푸드 딜리버리 서비스",
    description: "지역 맛집과 소비자를 연결하는 음식 배달 플랫폼입니다. 실시간 주문 추적 및 리뷰 시스템을 제공합니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["React Native", "Node.js", "MongoDB", "Google Maps API"],
    deadline: "2025-07-20",
    positions: ["모바일 개발자", "백엔드 개발자", "UI/UX 디자이너"],
    owner: {
      name: "임재현",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "9",
    title: "온라인 교육 플랫폼",
    description:
      "다양한 분야의 온라인 강의를 제공하는 교육 플랫폼입니다. 인터랙티브한 학습 경험과 진도 관리 기능을 제공합니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["Next.js", "Express", "MongoDB", "AWS"],
    deadline: "2025-08-15",
    positions: ["프론트엔드 개발자", "백엔드 개발자", "콘텐츠 기획자"],
    owner: {
      name: "오세진",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "10",
    title: "친환경 제품 마켓플레이스",
    description:
      "친환경 제품을 판매하고 구매할 수 있는 온라인 마켓플레이스입니다. 제품의 환경 영향을 투명하게 공개합니다.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    skills: ["React", "Node.js", "PostgreSQL", "Stripe API"],
    deadline: "2025-07-30",
    positions: ["프론트엔드 개발자", "백엔드 개발자", "마케팅 전문가"],
    owner: {
      name: "윤서연",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
]

export const mockMembers: Member[] = [
  {
    id: "1",
    name: "김개발",
    position: "프론트엔드 개발자",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "React와 TypeScript를 주로 사용하는 프론트엔드 개발자입니다. 사용자 경험을 중요시하며, 새로운 기술을 배우는 것을 좋아합니다.",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Node.js"],
    experience: "3년차",
    location: "서울특별시",
    email: "kim@example.com",
    github: "https://github.com/kimdev",
  },
  {
    id: "2",
    name: "이백엔드",
    position: "백엔드 개발자",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "Node.js와 Express를 사용한 백엔드 개발을 주로 하고 있습니다. 데이터베이스 설계와 API 개발에 관심이 많습니다.",
    skills: ["Node.js", "Express", "MongoDB", "PostgreSQL", "Docker"],
    experience: "5년차",
    location: "부산광역시",
    email: "lee@example.com",
    github: "https://github.com/leebackend",
  },
  {
    id: "3",
    name: "박풀스택",
    position: "풀스택 개발자",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "프론트엔드부터 백엔드까지 다양한 기술 스택을 다루는 개발자입니다. 새로운 프로젝트와 도전을 좋아합니다.",
    skills: ["React", "Node.js", "TypeScript", "MongoDB", "AWS", "Docker"],
    experience: "7년차",
    location: "대전광역시",
    email: "park@example.com",
    github: "https://github.com/parkfullstack",
    website: "https://parkdev.com",
  },
  {
    id: "4",
    name: "최디자인",
    position: "UI/UX 디자이너",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "사용자 중심의 디자인을 추구하는 UI/UX 디자이너입니다. 개발자와의 협업 경험이 풍부하며 프로토타이핑 툴에 능숙합니다.",
    skills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "HTML/CSS"],
    experience: "4년차",
    location: "서울특별시",
    email: "choi@example.com",
    website: "https://choiportfolio.com",
  },
  {
    id: "5",
    name: "정모바일",
    position: "모바일 개발자",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "Flutter와 React Native를 사용한 크로스 플랫폼 모바일 앱 개발을 전문으로 합니다. 사용자 친화적인 모바일 경험을 만들고자 합니다.",
    skills: ["Flutter", "React Native", "Swift", "Kotlin", "Firebase"],
    experience: "3년차",
    location: "인천광역시",
    email: "jung@example.com",
    github: "https://github.com/jungmobile",
  },
  {
    id: "6",
    name: "한기획",
    position: "기획자",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "IT 서비스 기획 및 프로젝트 관리를 담당하고 있습니다. 개발자와 디자이너 사이의 원활한 소통을 이끌어냅니다.",
    skills: ["서비스 기획", "프로젝트 관리", "마케팅", "데이터 분석", "Jira"],
    experience: "6년차",
    location: "경기도 성남시",
    email: "han@example.com",
  },
  {
    id: "7",
    name: "송데이터",
    position: "데이터 사이언티스트",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "데이터 분석과 머신러닝 모델 개발을 전문으로 합니다. 복잡한 문제를 데이터를 통해 해결하는 것을 좋아합니다.",
    skills: ["Python", "TensorFlow", "PyTorch", "SQL", "Data Visualization"],
    experience: "4년차",
    location: "대구광역시",
    email: "song@example.com",
    github: "https://github.com/songdata",
  },
  {
    id: "8",
    name: "임게임",
    position: "게임 개발자",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "Unity와 Unreal Engine을 사용한 게임 개발을 하고 있습니다. 재미있고 몰입감 있는 게임 경험을 만들고자 합니다.",
    skills: ["Unity", "C#", "Unreal Engine", "C++", "3D Modeling"],
    experience: "5년차",
    location: "경기도 성남시",
    email: "lim@example.com",
    github: "https://github.com/limgame",
  },
  {
    id: "9",
    name: "오블록체인",
    position: "블록체인 개발자",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "이더리움과 솔라나 기반의 dApp 개발을 전문으로 합니다. 블록체인 기술의 실용적인 적용에 관심이 많습니다.",
    skills: ["Solidity", "Web3.js", "Ethereum", "Smart Contracts", "DeFi"],
    experience: "3년차",
    location: "서울특별시",
    email: "oh@example.com",
    github: "https://github.com/ohblockchain",
  },
  {
    id: "10",
    name: "윤신입",
    position: "주니어 개발자",
    avatar: "/placeholder.svg?height=200&width=200",
    bio: "열정적인 주니어 개발자입니다. 웹 개발에 관심이 많으며 빠르게 성장하고 있습니다. 멘토링과 함께 성장할 수 있는 기회를 찾고 있습니다.",
    skills: ["JavaScript", "React", "HTML/CSS", "Git", "Node.js"],
    experience: "1년 미만",
    location: "광주광역시",
    email: "yoon@example.com",
    github: "https://github.com/yoonjunior",
  },
]
